const assert = require("node:assert/strict");

function nowIso() {
  return new Date().toISOString();
}

function uniqueId(prefix) {
  return `${prefix}-${Date.now()}-${Math.floor(Math.random() * 10000)}`;
}

async function run() {
  const db = require("../../../functions/dist/src/lib/db.js");

  const recipeId = uniqueId("smoke-recipe");
  const sessionId = uniqueId("smoke-session");
  const contentHash = uniqueId("hash");

  const recipe = {
    id: recipeId,
    title: "Smoke Test Recipe",
    description: "Recipe used by database smoke tests.",
    contentHash,
    steps: [
      {
        stepId: "step-1",
        instruction: "Mix ingredients.",
        expectedVisualState: "Ingredients are combined with no dry spots.",
        commonFailures: ["Too dry", "Too wet"],
        checkpointMinutes: 3
      }
    ]
  };

  const turn = {
    stepId: "step-1",
    promptedAt: nowIso(),
    verdict: "adjust",
    advice: "Add a tablespoon of water and continue mixing.",
    actualDurationMinutes: 2,
    imageBlobPath: "local/smoke/step-1.jpg"
  };

  const adjustment = {
    stepId: "step-1",
    type: "ingredient",
    description: "Added 1 tbsp water."
  };

  const personalizedRecipe = {
    title: "Smoke Test Recipe (Personalized)",
    personalizedSteps: [
      {
        stepId: "step-1",
        instruction: "Mix ingredients and rest 5 minutes.",
        note: "Hydration adjusted for user's flour."
      }
    ],
    notes: "Generated by smoke test."
  };

  await db.initializeDatabaseIfNeeded();

  await db.cacheRecipe(recipe);

  const fetchedRecipe = await db.getRecipe(recipeId);
  assert.equal(fetchedRecipe.id, recipeId, "getRecipe should return the inserted recipe");

  const fetchedStep = await db.getStep(recipeId, "step-1");
  assert.equal(fetchedStep.stepId, "step-1", "getStep should return expected step");

  const cachedByHash = await db.getCachedRecipe(contentHash);
  assert.ok(cachedByHash, "getCachedRecipe should return a recipe");
  assert.equal(cachedByHash.id, recipeId, "contentHash lookup should match inserted recipe");

  const allRecipes = await db.getRecipes();
  assert.ok(allRecipes.some((candidate) => candidate.id === recipeId), "getRecipes should include inserted recipe");

  await db.createSession(sessionId, recipeId);
  await db.appendTurn(sessionId, turn);
  await db.appendAdjustment(sessionId, adjustment);
  await db.savePersonalizedRecipe(sessionId, personalizedRecipe);

  const session = await db.getSession(sessionId);
  assert.equal(session.sessionId, sessionId, "getSession should return inserted session");
  assert.equal(session.recipeId, recipeId, "session recipeId should match");
  assert.ok(session.turns.length >= 1, "session should contain at least one turn");
  assert.ok(session.adjustments.length >= 1, "session should contain at least one adjustment");
  assert.ok(session.personalizedRecipe, "session should contain personalized recipe");

  console.log("DB smoke test passed.");
  console.log(`recipeId=${recipeId}`);
  console.log(`sessionId=${sessionId}`);
}

run().catch((error) => {
  console.error("DB smoke test failed.");
  console.error(error);
  process.exit(1);
});
